races = [
    "Aarakocra",
    "Aasimar",
    "Anão",
    "Bugbear",
    "Centauro",
    "Dhampir",
    "Draconato",
    "Elfo",
    "Fairy",
    "Firbolg",
    "Genasi",
    "Gith",
    "Gnomo",
    "Goblin",
    "Halfling",
    "Haregon",
    "HexBlood",
    "Híbrido Simic",
    "Hobgoblin",
    "Hollow One",
    "Humano",
    "Kalashtar",
    "Kenku",
    "Kobold",
    "Leonino",
    "Lizardfolk",
    "Locathah",
    "Loxodonte",
    "Meio-Elfo",
    "Meio-Orc",
    "Minotauro",
    "Orc",
    "Reborn",
    "Sátiro",
    "Shifter",
    "Tabaxi",
    "Tiefling",
    "Tortle",
    "Tritão",
    "Vedalken",
    "Verdan",
    "Warforged",
    "Yuan-Ti Puro"
]

subraces = {
    "Aasimar": ["Fallen Aasimar", "Protector Aasimar", "Scourge Aasimar"],
    "Anão": ["Gray Dwarves", "Hill Dwarves", "Mountain Dwarf", "Mark Of Warding"],
    "Draconato": ["Draconato Draconblood", "Draconato Ravenite"],
    "Elfo": ["Dark Elf(Drow)", "Eladrin", "High Elf", "Pallid Elf", "Sea Elf", "Shadar-Kai", "Wood Elf", "Mark of Shadow"],
    "Gnomo": ["Forest Gnomo", "Rock Gnomo", "Deep Gnomo (Svirfneblin)"],
    "Halfling": ["Lightfoot", "Lotusden", "Stout", "Mark of Healing", "Mark of Hospitality"],
    "Humano": ["Humano Padrão", "Humano Variante", "Mark of Finding", "Mark of Handling", "Mark of Making", "Mark of Passage", "Mark of Sentinel"],
    "Meio-Elfo": ["Mark of Detection", "Mark of Storm"],
    "Meio-Orc": ["Mark of Finding"],
    "Tiefling": ["Asmodeus", "Baalzebul", "Dispater", "Feral", "Fierna", "Glasya", "Levistus", "Mammon", "Mephistopheles", "Zariel"]
}
